# Generated by Django 4.2.6 on 2023-11-30 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='followerremote',
            name='url',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
