# Generated by Django 4.2.6 on 2023-11-25 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendfollowrequest',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
