# Generated by Django 4.2.6 on 2023-11-21 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_profile_is_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_approved',
            new_name='needs_approval',
        ),
    ]
