# Generated by Django 4.2.6 on 2023-11-22 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0003_rename_is_approved_profile_needs_approval'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='needs_approval',
            new_name='is_approved',
        ),
    ]
