# Generated by Django 4.2.6 on 2023-11-22 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0004_rename_needs_approval_profile_is_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_approved',
            new_name='approved',
        ),
    ]
