# Generated by Django 4.2.6 on 2023-11-22 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0005_rename_is_approved_profile_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_approval_required', models.BooleanField(default=True)),
            ],
        ),
    ]
