# Generated by Django 4.2.6 on 2023-11-26 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0005_followerremote_follower_followingremote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follower',
            name='followingRemote',
        ),
        migrations.AddField(
            model_name='followerremote',
            name='following_author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='author.profile'),
        ),
        migrations.AddField(
            model_name='followerremote',
            name='remote_id',
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AlterField(
            model_name='followerremote',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
