# Generated by Django 4.2.6 on 2023-11-27 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("author", "0006_remove_follower_followingremote_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RemoteFriendFollowRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("summary", models.CharField(max_length=200)),
                ("follower", models.CharField(default=None, max_length=300)),
                ("status", models.CharField(default="pending", max_length=20)),
                (
                    "followee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="author.profile"
                    ),
                ),
            ],
        ),
    ]
