# Generated by Django 4.2.6 on 2023-11-29 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Node",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("url", models.URLField()),
                ("username", models.CharField(max_length=200)),
                ("password", models.CharField(max_length=200)),
                ("outbound_username", models.CharField(max_length=200, null=True)),
                ("outbound_password", models.CharField(max_length=200, null=True)),
                ("use_authentication", models.BooleanField(default=False)),
            ],
        ),
    ]
