# Generated by Django 4.2.6 on 2023-12-04 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="token",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
