# Generated by Django 4.2.6 on 2023-11-13 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='use_authentication',
            field=models.BooleanField(default=False),
        ),
    ]
