# Generated by Django 4.2.6 on 2023-12-03 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0002_alter_remotecomment_author_alter_remotecomment_post_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RemotePost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("post_id", models.CharField(default=None, max_length=300)),
            ],
        ),
    ]
