# Generated by Django 4.2.6 on 2023-11-18 03:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0002_category_remove_post_origin_remove_post_source_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="id",
            field=models.CharField(
                default=uuid.uuid4,
                editable=False,
                max_length=200,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
