# Generated by Django 4.2.6 on 2023-11-27 02:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("author", "0007_remotefriendfollowrequest"),
        ("post", "0003_alter_comment_contenttype"),
    ]

    operations = [
        migrations.CreateModel(
            name="RemoteLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("summary", models.CharField(max_length=200)),
                ("post", models.CharField(max_length=200)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="author.profile"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RemoteComment",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=200,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField()),
                ("post", models.CharField(max_length=200)),
                ("published", models.DateTimeField(auto_now_add=True)),
                ("contentType", models.CharField(max_length=200)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="author.profile"
                    ),
                ),
            ],
        ),
    ]
