# Generated by Django 4.2.6 on 2023-11-21 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0003_alter_comment_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="like",
            name="object",
        ),
        migrations.DeleteModel(
            name="Liked",
        ),
    ]
