# Generated by Django 4.2.6 on 2023-11-20 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_comment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_file',
            field=models.FileField(blank=True, null=True, upload_to='media/post_images'),
        ),
        migrations.AddField(
            model_name='post',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
