# Generated by Django 4.2.6 on 2023-12-03 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0003_remotepost"),
    ]

    operations = [
        migrations.CreateModel(
            name="RemoteCommentLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("summary", models.CharField(max_length=200)),
                ("author", models.CharField(max_length=300)),
                (
                    "comment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="post.remotecomment",
                    ),
                ),
            ],
        ),
    ]
