# Generated by Django 4.2.6 on 2023-11-22 03:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0004_remove_like_object_delete_liked"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="id",
            field=models.CharField(
                default=uuid.uuid4, max_length=200, primary_key=True, serialize=False
            ),
        ),
    ]
