# Generated by Django 4.2.6 on 2023-11-29 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_remotelike_remotecomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(max_length=10000),
        ),
    ]
