# Generated by Django 4.2.6 on 2023-11-20 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post_image_file_post_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_file',
            field=models.FileField(blank=True, null=True, upload_to='post_images'),
        ),
    ]
