# Generated by Django 4.2.6 on 2023-11-20 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_post_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads'),
        ),
    ]
