# Generated by Django 4.2.6 on 2023-11-24 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_post_id'),
        ('post', '0007_commentlike'),
    ]

    operations = [
    ]
