# Generated by Django 4.2.6 on 2023-11-24 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_merge_0005_alter_post_id_0007_commentlike'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likedPosts', models.ManyToManyField(blank=True, related_name='liked_posts', to='post.like')),
            ],
        ),
    ]
