# Generated by Django 4.2.6 on 2023-11-24 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0009_remove_commentlike_object_alter_commentlike_id_liked"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commentlike",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
