# Generated by Django 4.2.6 on 2023-11-24 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0009_liked"),
        ("post", "0010_alter_commentlike_id"),
    ]

    operations = []
