# Generated by Django 4.2.6 on 2023-11-24 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0011_merge_0009_liked_0010_alter_commentlike_id"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Liked",
        ),
    ]
