# Generated by Django 4.2.6 on 2023-11-29 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("post", "0001_initial"),
        ("author", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RemoteInbox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("items", models.JSONField(blank=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="author.profile"
                    ),
                ),
                (
                    "requests",
                    models.ManyToManyField(
                        blank=True, to="author.remotefriendfollowrequest"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Inbox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "comment_likes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="rec_comment_likes",
                        to="post.commentlike",
                    ),
                ),
                (
                    "comments",
                    models.ManyToManyField(
                        blank=True, related_name="rec_comments", to="post.comment"
                    ),
                ),
                (
                    "follows",
                    models.ManyToManyField(
                        blank=True, related_name="rec_follows", to="author.profile"
                    ),
                ),
                (
                    "likes",
                    models.ManyToManyField(
                        blank=True, related_name="rec_likes", to="post.like"
                    ),
                ),
                (
                    "posts",
                    models.ManyToManyField(
                        blank=True, related_name="rec_posts", to="post.post"
                    ),
                ),
                (
                    "requests",
                    models.ManyToManyField(
                        blank=True,
                        related_name="rec_requests",
                        to="author.friendfollowrequest",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inbox_owner",
                        to="author.profile",
                    ),
                ),
            ],
        ),
    ]
