# Generated by Django 4.2.6 on 2023-12-03 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0003_remotepost"),
        ("inbox", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="remoteinbox",
            name="items",
        ),
        migrations.AddField(
            model_name="remoteinbox",
            name="comments",
            field=models.ManyToManyField(to="post.remotecomment"),
        ),
        migrations.AddField(
            model_name="remoteinbox",
            name="likes",
            field=models.ManyToManyField(to="post.remotelike"),
        ),
        migrations.AddField(
            model_name="remoteinbox",
            name="posts",
            field=models.ManyToManyField(to="post.remotepost"),
        ),
    ]
