# Generated by Django 4.2.6 on 2023-11-26 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("author", "0006_remove_follower_followingremote_and_more"),
        ("inbox", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RemoteInboxItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="RemoteInbox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="author.profile"
                    ),
                ),
                (
                    "items",
                    models.ManyToManyField(blank=True, to="inbox.remoteinboxitem"),
                ),
            ],
        ),
    ]
