# Generated by Django 4.2.6 on 2023-11-26 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inbox", "0002_remoteinboxitem_remoteinbox"),
    ]

    operations = [
        migrations.AddField(
            model_name="remoteinboxitem",
            name="type",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
