# Generated by Django 4.2.6 on 2023-11-26 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inbox", "0003_remoteinboxitem_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="remoteinboxitem",
            name="type",
            field=models.CharField(max_length=200),
        ),
    ]
