# Generated by Django 4.2.6 on 2023-11-26 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inbox", "0004_alter_remoteinboxitem_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="remoteinbox",
            old_name="author",
            new_name="local_author",
        ),
    ]
