# Generated by Django 4.2.6 on 2023-11-26 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inbox", "0005_rename_author_remoteinbox_local_author"),
    ]

    operations = [
        migrations.RenameField(
            model_name="remoteinboxitem",
            old_name="url",
            new_name="id_url",
        ),
    ]
