# Generated by Django 4.2.6 on 2023-11-26 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inbox", "0006_rename_url_remoteinboxitem_id_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="remoteinbox",
            old_name="local_author",
            new_name="author",
        ),
    ]
