# Generated by Django 4.2.6 on 2023-11-27 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("author", "0007_remotefriendfollowrequest"),
        ("inbox", "0007_rename_local_author_remoteinbox_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="remoteinbox",
            name="requests",
            field=models.ManyToManyField(
                blank=True, to="author.remotefriendfollowrequest"
            ),
        ),
    ]
