# Generated by Django 4.2.6 on 2023-11-27 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inbox", "0009_rename_id_url_remoteinboxitem_object_url_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="remoteinbox",
            name="items",
        ),
        migrations.DeleteModel(
            name="RemoteInboxItem",
        ),
        migrations.AddField(
            model_name="remoteinbox",
            name="items",
            field=models.JSONField(default=list),
        ),
    ]
