
# Generated by Django 4.2.6 on 2023-11-28 21:26

# Generated by Django 4.2.6 on 2023-11-27 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0011_alter_remoteinbox_items'),
        ("inbox", "0011_alter_remoteinbox_items"),
    ]

    operations = [
        migrations.AlterField(
            model_name='remoteinbox',
            name='items',
            model_name="remoteinbox",
            name="items",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
