# Generated by Django 3.1.6 on 2023-10-16 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.CharField(max_length=200)),
                ('host', models.CharField(max_length=200)),
                ('display', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('github', models.CharField(max_length=200)),
                ('profile_image', models.IntegerField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower_id', models.CharField(max_length=200)),
                ('host', models.CharField(max_length=200)),
                ('display', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('github', models.CharField(max_length=200)),
                ('profile_image', models.IntegerField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('source', models.CharField(max_length=200)),
                ('origin', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('content_type', models.CharField(max_length=200)),
            ],
        ),
    ]
