# Generated by Django 3.1.6 on 2023-10-16 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profile_image',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='follower',
            name='profile_image',
            field=models.IntegerField(),
        ),
    ]
