# Generated by Django 4.2.6 on 2023-10-28 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0004_follower_delete_followers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="follower",
            name="followers",
            field=models.ManyToManyField(
                blank=True, related_name="followed_by", to="social.follower"
            ),
        ),
    ]
