# Generated by Django 4.2.6 on 2023-10-28 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0006_alter_follower_followers"),
    ]

    operations = [
        migrations.RenameField(
            model_name="follower",
            old_name="followers",
            new_name="following",
        ),
    ]
