# Generated by Django 4.2.6 on 2023-10-30 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_likes_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='social.post'),
        ),
        migrations.AlterField(
            model_name='likes',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.profile'),
        ),
    ]
