# Generated by Django 4.2.6 on 2023-10-29 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0010_alter_follower_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.TextField(blank=True),
        ),
    ]
