# Generated by Django 4.2.6 on 2023-10-30 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_likes_post_alter_likes_author'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Likes',
            new_name='Like',
        ),
    ]
