# Generated by Django 4.2.6 on 2023-11-01 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0011_alter_profile_bio'),
        ('social', '0011_rename_likes_like'),
    ]

    operations = [
    ]
