# Generated by Django 4.2.6 on 2023-11-10 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0013_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.ManyToManyField(blank=True, related_name='rec_comments', to='social.comment')),
                ('follows', models.ManyToManyField(blank=True, related_name='rec_follows', to='social.profile')),
                ('likes', models.ManyToManyField(blank=True, related_name='rec_likes', to='social.post')),
                ('posts', models.ManyToManyField(blank=True, related_name='rec_posts', to='social.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.profile')),
            ],
        ),
    ]
