# Generated by Django 4.2.6 on 2023-11-10 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0015_alter_inbox_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='rec_likes', to='social.like'),
        ),
    ]
