# Generated by Django 4.2.6 on 2023-11-11 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0016_alter_inbox_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='requests',
            field=models.ManyToManyField(blank=True, related_name='rec_requests', to='social.friendfollowrequest'),
        ),
    ]
